<?php
$feedcategories= array(

array ( Name => "Action",
Slug => "action",
Heyzap => true,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Adventure",
Slug => "adventure",
Heyzap => true,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "All Time Best",
Slug => "popular",
Heyzap => true,
Mochi => false,
Status  => "",
Mapping => "",
Info => "(HeyZap only)"),

array ( Name => "Board Game",
Slug => "boardgame",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Casino",
Slug => "casino",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Customize",
Slug => "customize",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Dress-Up",
Slug => "dressup",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Driving",
Slug => "driving",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Education",
Slug => "education",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Featured",
Slug => "featured",
Heyzap => true,
Mochi => false,
Status  => "",
Mapping => "",
Info => "(HeyZap only)"),


array ( Name => "Fighting",
Slug => "fighting",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Hot Right Now",
Slug => "hot_new",
Heyzap => true,
Mochi => false,
Status  => "",
Mapping => "",
Info => "(HeyZap only)"),


array ( Name => "Jigsaw",
Slug => "jigsaw",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),
  
array ( Name => "Life & Style",
Slug => "lifestyle",
Heyzap => true,
Mochi => false,
Status  => "",
Mapping => "",
Info => "(HeyZap only)"),

array ( Name => "Multiplayer",
Slug => "multiplayer",
Heyzap => true,
Mochi => false,
Status  => "",
Mapping => "",
Info => "(HeyZap only)"),

array ( Name => "Other",
Slug => "other",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Puzzles",
Slug => "puzzles",
Heyzap => true,
Mochi => true,
Status  => "",
Mapping => "",
Info => "(Puzzle on HeyZap)"),

array ( Name => "Rhythm",
Slug => "rythm",
Heyzap => false,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),

array ( Name => "Shooting",
Slug => "shooting",
Heyzap => true,
Mochi => true,
Status  => "",
Mapping => "",
Info => "(Shooter on HeyZap)"),

array ( Name => "Social",
Slug => "social",
Heyzap => true,
Mochi => false,
Status  => "",
Mapping => "",
Info => "(HeyZap only)"),

array ( Name => "Sports",
Slug => "sports",
Heyzap => true,
Mochi => true,
Status  => "",
Mapping => "",
Info => ""),
     
array ( Name => "Strategy",
Slug => "strategy",
Heyzap => true,
Mochi => true,
Status  => "",
Mapping => "",
Info => "")
);
?>