<?php
/**
 * MyArcadePlugin Default Categories
 *
 * @author Daniel Bakovic <contact@myarcadeplugin.com>
 * @copyright (c) 2013, Daniel Bakovic
 * @license http://myarcadeplugin.com
 * @package MyArcadePlugin/Modules/IBPArcadeScores
 */

$feedcategories= array(

array ( 'Name' => "Action",
'ID' => 0,
'Slug' => "action",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true,
'FOG' => false,
'Spilgames' => array( 'id' => '1', 'name' => 'Action Games'),
'BigFish' => '1',
'Scirra'  => true,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Adventure",
'ID' => 1,
'Slug' => "adventure",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true,
'FOG' => true,
'Spilgames' => array( 'id' => '45', 'name' => 'Adventure Games'),
'BigFish' => '21',
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Arcade",
'ID' => 1,
'Slug' => "arcade",
'Mochi' => false,
'Kongregate' => false,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Board Game",
'ID' => 3,
'Slug' => "boardgame",
'Mochi' => true,
'Kongregate' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => array( 'id' =>'55,56,59,62,63', 'name' => 'Mahjong Games,Bubble Shooter,Board and Card Games,Match-3 Games,Sudoku Games'),
'BigFish' => '3,5,6,17,18,19',
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Casino",
'ID' => 4,
'Slug' => "casino",
'Mochi' => true,
'Kongregate' => false,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Defense",
'ID' => 1,
'Slug' => "defense",
'Mochi' => false,
'Kongregate' => false,
'FGD' => true,
'FOG' => true,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Customize",
'ID' => 5,
'Slug' => "customize",
'Mochi' => true,
'Kongregate' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Dress-Up",
'ID' => 6,
'Slug' => "dressup",
'Mochi' => true,
'Kongregate' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => array( 'id' =>'24,29,31,32,58', 'name' => 'Girls Games,Make Over Games,Dress Up Games,Make Up Games,Celebrity Games'),
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Driving",
'ID' => 7,
'Slug' => "driving",
'Mochi' => true,
'Kongregate' => false,
'FGD' => true,
'FOG' => true,
'Spilgames' => array( 'id' =>'4,57', 'name' => 'Racing Games,Uphill Racing'),
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Education",
'ID' => 8,
'Slug' => "education",
'Mochi' => true,
'Kongregate' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Fighting",
'ID' => 10,
'Slug' => "fighting",
'Mochi' => true,
'Kongregate' => false,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Jigsaw",
'ID' => 12,
'Slug' => "jigsaw",
'Mochi' => true,
'Kongregate' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Multiplayer",
'ID' => 14,
'Slug' => "multiplayer",
'Mochi' => false,
'Kongregate' => true,
'FGD' => true,
'FOG' => true,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => "(Kongregate & FGD)"),

array ( 'Name' => "Other",
'ID' => 15,
'Slug' => "other",
'Mochi' => true,
'Kongregate' => false,
'FGD' => true,
'FOG' => array ('Flying', '3D'),
'Spilgames' => array( 'id' =>'36,46,47,54,61,60', 'name' => 'Fun Games,Animal Games,Skill Games,Hidden Objects,Cooking Games,HTML5 Games'),
'BigFish' => false,
'Scirra'  => true, /* Rotary */
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Puzzles",
'ID' => 16,
'Slug' => "puzzles",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true, /*Puzzle*/
'FOG' => true, /*Puzzle*/
'Spilgames' => array( 'id' =>'3,49', 'name' => 'Puzzle Games,Physics Games'),
'BigFish' => '4',
'Scirra'  => true,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Rhythm",
'ID' => 17,
'Slug' => "rythm",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => "(Music on Kongregate)"),

array ( 'Name' => "Shooting",
'ID' => 18,
'Slug' => "shooting",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true, /*Shooter*/
'FOG' => true,
'Spilgames' => array( 'id' =>'48', 'name' => 'Shooting Games'),
'BigFish' => false,
'Scirra'  => true, /*Shooter*/
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Sports",
'ID' => 20,
'Slug' => "sports",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true,
'FOG' => true,
'Spilgames' => array( 'id' =>'6', 'name' => 'Sports Games'),
'BigFish' => false,
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Strategy",
'ID' => 21,
'Slug' => "strategy",
'Mochi' => true,
'Kongregate' => true,
'FGD' => true,
'FOG' => false,
'Spilgames' => array( 'id' =>'18,50,53', 'name' => 'Simulation Games,Tower Defense,Time Management'),
'BigFish' => '15,25,29',
'Scirra'  => false,
'Status'  => "",
'Mapping' => "",
'Info' => "")
);